# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install system deps
        run: |
          sudo apt-get update -y -qq --fix-missing
          sudo apt-get install -y wget gnupg
          sudo echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >> /etc/apt/sources.list.d/pgdg.list
          sudo wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
          sudo apt update
          sudo apt-get update -y --fix-missing
          sudo apt-get install -y curl

          sudo apt-get install -y git
          sudo apt-get install -y clang-9 llvm-9 gcc make build-essential libz-dev zlib1g-dev strace libssl-dev pkg-config postgresql-13 postgresql-server-dev-13 ruby ruby-dev rubygems build-essential
      - name: Install system deps
        run: |
          RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
          ENV PATH="/home/${USER}/.cargo/bin:${PATH}"
          cargo install cargo-pgx
          cargo install cargo-deb
          cargo pgx init --pg13=/usr/lib/postgresql/13/bin/pg_config
