# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-alpine:
    runs-on: ubuntu-latest
    container: postgres:13-alpine
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: |
          apk add --no-cache \
          git \
          curl \
          bash \
          ruby-dev \
          ruby-etc \
          musl-dev \
          make \
          gcc \
          coreutils \
          util-linux-dev \
          musl-dev \
          openssl-dev \
          clang-libs \
          tar

      - name: install fpm gem
        run: gem install --no-document fpm

      - name: install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
          PATH="$HOME/.cargo/bin:${PATH}"
          source $HOME/.cargo/env
          cargo install cargo-pgx
          cargo pgx init --pg13=$(which pg_config)

      - name: build apk
        run: |
          fpm \
          -s dir \
          -t apk \
          -n grpc_fdw-13 \
          -v 0.0.1 \
          -p ./grpc_fdw_13-0.0.1.$(uname -m).apk \
          -a $(uname -m) \
          ./build/target/release/grpc_fdw-pg13

      - name: Archive pkg
        uses: actions/upload-artifact@v2
        with:
          name: grpc-fdw_alpine-pkg
          path: ./*.apk

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: update apt
        run: sudo apt-get update -y -qq --fix-missing

      - name: install postgres build dependencies
        run: sudo apt-get install -y clang-10 llvm-10 clang gcc make build-essential libz-dev zlib1g-dev strace libssl-dev pkg-config postgresql-13 postgresql-server-dev-13 curl

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
          PATH="/home/${USER}/.cargo/bin:${PATH}"
          cargo install cargo-pgx
          cargo install cargo-deb
          cargo pgx init --pg13=/usr/lib/postgresql/13/bin/pg_config

      - name: build pkg
        run: |
          cargo pgx package
          cargo deb

      - name: Archive pkg
        uses: actions/upload-artifact@v2
        with:
          name: grpc-fdw_pkg
          path: target/debian/*.deb
